server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    platform: postgres
    username: postgres
    password: mysecretpassword
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
